algoritmo "Algoritmo soma de matriz"
// Função :
// Autor :
// Data : 16/06/2026
// Seção de Declarações
var

a, b, c : vetor [1..3, 1..3] de inteiro
i, j : inteiro

inicio
// Seção de Comandos

para i de 1 ate 3 faca
    para j de 1 ate 3 faca
        a[i,j] <- i + j
        b[i,j] <- i + j
    fimpara
fimpara

para i de 1 ate 3 faca
    para j de 1 ate 3 faca
        c[i,j] <- a[i,j] + b[i,j]
    fimpara
fimpara

escreva("dasdasdasdas")


fimalgoritmo